#!/usr/bin/env bash

if [ "$1" = "-k" ]; then
  tvname=2
else
  tvname=\"$1\"
fi

read -d '' APPLESCRIPT <<EOF
set _major to (system attribute "sys1")
set _minor to (system attribute "sys2")
set _isElCapitan to _major = 10 and _minor = 11
set _isSierra_or_later to _major > 10 or _major = 10 and _minor >= 12

tell application "System Events"
    tell process "SystemUIServer"
        if _isElCapitan then
            tell (menu bar item 1 of menu bar 1 whose description contains "Displays Menu")
                select
                    delay 0.1
                    key code 125 using command down
                    delay 0.1
                    click menu item $tvname of menu 1
            end tell
        else if _isSierra_or_later then
            if $tvname = 2 then
                set tvname to "Turn AirPlay Off"
            else
                set tvname to $tvname
            end if
            click (menu bar item 1 of menu bar 1 whose description contains "Displays")
            set mymenu to result
            delay 0.5
            repeat with myitem in (menu items of menu of mymenu)
                set myname to name of myitem
                if myname = tvname then
                    click myitem
                    exit
                end if
            end repeat
        else
            click (menu bar item 1 of menu bar 1 whose description contains "Displays")
            click menu item $tvname of menu 1 of result
        end if
    end tell
end tell
EOF

osascript -e "$APPLESCRIPT" > /dev/null
